# fly.toml app configuration file generated for rcverse on 2024-03-08T01:02:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rcverse'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# We reached error when everyone joined during a presentation:
#
#     Instance 6e82403da07628 reached hard limit of 25 concurrent connections.
#     This usually indicates your app is not closing connections properly or is
#     not closing them fast enough for the traffic levels it is handling. Scaling
#     resources, number of instances or increasing your hard limit might help.
#
# https://fly.io/docs/reference/load-balancing/#web-service
#
# Also note: It appears that since I have a [http_service] section, [services] is
#            ignored? Originally tried these exact settings in
#            [connections.concurrency]
[http_service.concurrency]
  type = "requests"
  hard_limit = 200
  soft_limit = 100
